services:
  - type: web
    name: global-tech-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: global-tech-db
          property: connectionString

databases:
  - name: global-tech-db
    databaseName: global_tech
    user: global_tech_user
    plan: free